#!/usr/bin/env bash
# scripts/init-mac-ssh.sh
# One-shot Mac-side setup for the husn.io SSH alias.
# Run from your Mac (NOT the server):
#   curl -fsSL https://raw.githubusercontent.com/usman3656/husn_product_mvp/main/scripts/init-mac-ssh.sh | bash
#
# What it does:
#   - Creates ~/.ssh if missing
#   - Backs up an existing ~/.ssh/config to ~/.ssh/config.bak.<timestamp>
#   - Writes a fresh ~/.ssh/config with sane keepalive defaults + a `husn` host
#     alias so `ssh husn` connects to the production box without timing out
#   - chmod 600
#
# Safe to re-run.

set -euo pipefail

CFG="$HOME/.ssh/config"
mkdir -p "$HOME/.ssh"
chmod 700 "$HOME/.ssh"

if [[ -f "$CFG" ]]; then
  ts=$(date -u +%Y%m%dT%H%M%SZ)
  cp "$CFG" "$CFG.bak.$ts"
  echo "Backed up existing ~/.ssh/config to ~/.ssh/config.bak.$ts"
fi

cat > "$CFG" <<EOF
# Generated by scripts/init-mac-ssh.sh.
# Global defaults: keep idle connections alive across NAT timeouts.
Host *
    ServerAliveInterval 60
    ServerAliveCountMax 60
    TCPKeepAlive yes
    ConnectTimeout 10

# husn.io production box on Hetzner.
# IdentityFile is intentionally omitted: ssh will try every key under
# ~/.ssh/id_* (ed25519, rsa, ecdsa) plus anything loaded into ssh-agent.
# That way the alias works regardless of how the user named their key.
Host husn
    HostName 178.105.157.152
    User root
EOF

chmod 600 "$CFG"

echo "Wrote $CFG"
echo "Try:  ssh husn"
